### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/contexture-elasticsearch#147]
This issue is tracking the 1.0 release instead of having a single PR with all the changes.

- [x] Fixes #128 ES7 and new client support (PR #145)
- [x] Fixes #123 Changelog improvements (PR #148)
- [x] Fixes #131 Remove last bit of non fp lodash (PR #148)
- [x] Rename all uses of `context` to `node` (PR #148)
- [x] Reconsider options.requestorContext and config.request (PR #148)
- [x] Fixes #146 Clean up readme (PR #148)
- [x] Fixes #94 and Fixes #23 Remove field mode stuff (PR #150)
  Moving forward, we can assume that this works with something that processes the mappings and therefore tells us what the analyzed field paths are
- [x] Kill support for verbose/summaryView/forceExclude on results (deprecated in favor of include/exclude), etc (PR #148)
- [x] ~(Optionally?) Log ES errors to the console`~
  ~This PR improves error handling by making it continue to other nodes gracefully instead of hard crashing and also makes it more debuggable but effectively suppresses the errors from an ops perspective (details in the PR)~ decided not to worry since the web app logs are not where you'd expect this to be anyway.
- [x] Fixes #88 Remove order from schema generation (as it is a UI concern and no longer relevant)
- [ ] Kill older example types
  Since this is a 1.0 release, we might want to remove the myriad of miscellaneous example types that are no longer using in any of our apps. I doubt they are used externally, but just in case, a major semver release is the time to rip them out. They aren't able to be as thoroughly tested against ES 7 since there's no real-world usage we know of - which makes now a logical time to remove them.
- [ ] Drop ES 6
  We are able to maintain backward compatibility with only two small additions (so far), but removing that would mean a 2.0 release later down the line (and would mean that we'd need probably need all new additions to be tested on ES 6 for all of 1.x)
- [ ] #93 Maybe finally do something about results's context.response thing (requires updating contexture-client, contexture-react, and probably app usage)
- [ ] Revisit the sequentialResultTest utilities in unit tests
- [ ] Generally, kill all legacy stuff
